# Generated by Django 5.0.6 on 2024-07-11 04:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=13)),
                ('desc', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=240)),
                ('first_name', models.CharField(max_length=240)),
                ('last_name', models.CharField(max_length=240)),
                ('contact_no', models.CharField(max_length=240)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RideModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=120)),
                ('car_id', models.CharField(max_length=120)),
                ('details', models.CharField(max_length=250)),
                ('date_of_trip', models.DateField(default=django.utils.timezone.now)),
                ('time_of_trip', models.TimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('vacant_seats', models.IntegerField()),
                ('price', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riders_id', models.IntegerField(blank=True, null=True)),
                ('seats_booked', models.IntegerField(blank=True, default=0, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expressapp.ridemodel')),
            ],
        ),
    ]
